In [1]:
import tensorflow as tf

In [2]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31]

tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [3]:
for sales in tf_dataset:
    print(sales.numpy())

21
22
-108
31
-1
32
34
31


In [4]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


In [5]:
for sales in tf_dataset.take(3):
    print(sales.numpy())

21
22
-108


In [6]:
tf_dataset = tf_dataset.filter(lambda x: x>0)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
31
32
34
31


In [7]:
tf_dataset = tf_dataset.map(lambda x: x*72)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1512
1584
2232
2304
2448
2232


In [8]:
tf_dataset = tf_dataset.shuffle(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1584
1512
2304
2232
2232
2448


In [9]:
for sales_batch in tf_dataset.batch(2):
    print(sales_batch.numpy())

[1584 2232]
[1512 2448]
[2232 2304]


In [10]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*72).shuffle(2).batch(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1512 2232]
[1584 2448]
[2304 2232]


In [13]:
import glob, os
print(len(glob.glob(r'C:/Users/Timothy/breast cancer/training/jpeg/*')))
# should print the number of JPEGs you expect


10237


In [14]:
image_count = len(images_ds)
image_count

10237

In [15]:
type(images_ds)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

In [16]:
images_ds = images_ds.shuffle(200)
for file in images_ds.take(3):
    print(file.numpy())

b'C:\\Users\\Timothy\\breast cancer\\training\\jpeg\\1-004_14.jpg'
b'C:\\Users\\Timothy\\breast cancer\\training\\jpeg\\1-005_8.jpg'
b'C:\\Users\\Timothy\\breast cancer\\training\\jpeg\\1-002_7.jpg'


In [17]:
class_names = ["Bening","Malignant"]

In [18]:
train_size = int(image_count*0.8)
train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [19]:
len(train_ds)

8189

In [22]:
len(test_ds)

2048

In [23]:
def get_label(file_path):
    import os
    parts = tf.strings.split(file_path, os.path.sep)
    return parts[-2]

In [27]:
get_label("C:\\Users\\Timothy\\breast cancer\\training\\jpeg\\1-008.jpg")

<tf.Tensor: shape=(), dtype=string, numpy=b'jpeg'>

In [25]:
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path) # load the raw data from the file as a string
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img, [128, 128])
    return img, label

In [28]:
img, label = process_image("C:\\Users\\Timothy\\breast cancer\\training\\jpeg\\1-008.jpg")
img.numpy()[:2]

array([[[60.01706 ],
        [57.839844],
        [54.240845],
        [56.577576],
        [55.762573],
        [61.961243],
        [72.570465],
        [74.52908 ],
        [67.86127 ],
        [60.01126 ],
        [55.282898],
        [50.548615],
        [47.063812],
        [49.263733],
        [54.142212],
        [52.305603],
        [53.51953 ],
        [49.71585 ],
        [40.557373],
        [39.929993],
        [43.452484],
        [46.32257 ],
        [45.762085],
        [45.77823 ],
        [49.14853 ],
        [54.05008 ],
        [54.586823],
        [47.729614],
        [38.188324],
        [35.735718],
        [35.017975],
        [32.096375],
        [31.171875],
        [31.317963],
        [29.210938],
        [25.926056],
        [24.480469],
        [31.038757],
        [36.461304],
        [37.156464],
        [31.49295 ],
        [30.492188],
        [30.928864],
        [23.598083],
        [17.855164],
        [16.411774],
        [16.252747],
        [20.0

In [33]:
import tensorflow as tf

# Option 1: This is the best approach for TensorFlow datasets
def process_image(image, label):
    # Process the image
    # For example, normalize the image
    processed_image = tf.cast(image, tf.float32) / 255.0  # Example processing
    return processed_image, label

# Apply the function to the datasets
train_ds = train_ds.map(process_image)
test_ds = test_ds.map(process_image)

# Alternative approach if you need a single-argument function:
def process_image_alt(inputs):
    # Use indexing instead of unpacking
    image = inputs[0]
    label = inputs[1]
    # Process the image
    processed_image = tf.cast(image, tf.float32) / 255.0  # Example processing
    return processed_image, label

# Apply the alternative function
# train_ds = train_ds.map(process_image_alt)
# test_ds = test_ds.map(process_image_alt)

In [34]:
for image, label in train_ds.take(1):
    print("****",image)
    print("****",label)

**** tf.Tensor(
[[[0.30604798]
  [0.31769985]
  [0.35574892]
  ...
  [0.2889025 ]
  [0.30860883]
  [0.31463277]]

 [[0.23722738]
  [0.3338391 ]
  [0.3036074 ]
  ...
  [0.29159176]
  [0.28950626]
  [0.22754432]]

 [[0.23839255]
  [0.26669288]
  [0.3327042 ]
  ...
  [0.32679084]
  [0.3456324 ]
  [0.26026097]]

 ...

 [[0.2302799 ]
  [0.20771196]
  [0.16489485]
  ...
  [0.382096  ]
  [0.3736054 ]
  [0.29027662]]

 [[0.20307893]
  [0.17846178]
  [0.20111276]
  ...
  [0.35730496]
  [0.36976102]
  [0.30711982]]

 [[0.19875069]
  [0.1472138 ]
  [0.20482837]
  ...
  [0.44777438]
  [0.3454299 ]
  [0.37299493]]], shape=(128, 128, 1), dtype=float32)
**** tf.Tensor(b'jpeg', shape=(), dtype=string)


In [35]:
def scale(image, label):
    return image/255, label

In [36]:
train_ds = train_ds.map(scale)

In [37]:
for image, label in train_ds.take(5):
    print("****Image: ",image.numpy()[0][0])
    print("****Label: ",label.numpy())

****Image:  [0.00144896]
****Label:  b'jpeg'
****Image:  [0.0006153]
****Label:  b'jpeg'
****Image:  [0.00392157]
****Label:  b'jpeg'
****Image:  [0.]
****Label:  b'jpeg'
****Image:  [0.00392157]
****Label:  b'jpeg'
